### PR TITLE
Add fetch/diff tools and new formatting check

### PR DESCRIPTION
**Pull request by jackdunger**
Adds tools to:
* fetch a remote
* get a list of changed files
* get the diff for a file

New Test:
* Looks for new tabs, bad ASCII chars (0x00->0x09, 0x0b-0x1f, 0x7f), missing EOF newlines and EOL whitespace
* single instance fails test
* Prints a list of errors by file to html
* Clones from URL of master, fetches from another and examines the new lines in changed files with extensions .hh,  .h,  .cc,  .c,  .py 
The functions have been tested locally, but the integration into cog has not..

### CODE REVIEW

**Comment by jackdunger** [comment]
addresses #3 @straitm

**Comment by jackdunger** [comment]
@mastbaum is cog using python 2.6? i think the check_output call needs 2.7..

**Comment by mastbaum** [comment]
I'm running Python 2.7.6 on the build test nodes at Penn, so no problem.

**Comment by jackdunger** [comment]
Ok thanks. This needs a brush up before review, it might be an old branch

**Comment by jackdunger** [comment]
@mastbaum this is ready to go. It works locally if I manually put in the sha/urls etc.
I've also added a wrapper on check_output so that the cmd output is consistent.

**Comment by mastbaum** [comment]
Thanks, @jackdunger. Just tested (see [here](http://snopl.us/code/ondemand/record/178ea9f44994d156407f0eec545b19f015758e8a)), looks good!

**Comment by jackdunger** [comment]
@mastbaum cheers! Let me know when its up and running and ill add a commit to rat #1176 for a final check.

**Pull request merged**
